name: Build

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # يعمل كل أحد عند الساعة 00:00.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # تنزيل الكود من المستودع

      # إعداد Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          channel: stable  # استخدام قناة stable
          flutter-version: '3.19.0'  # تحديد إصدار Flutter (اختياري)
          architecture: X64  # تحديد بنية النظام (X64 أو arm64)

      # إعداد Node.js (إذا كان ضروريًا لـ npm)
      - uses: actions/setup-node@v4
        with:
          node-version: '18'  # تحديد إصدار Node.js

      - run: flutter pub get  # تثبيت التبعيات باستخدام Flutter
      - run: flutter analyze --fatal-infos  # تحليل الكود
      - run: dart tool/sig.dart --verify  # إذا كان هذا الأمر لا يتطلب Flutter
      - run: npm run build  # بناء المشروع (إذا كان يستخدم Node.js)
