name: Build

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # تشغيل كل أحد عند منتصف الليل

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # تعديل: إذا كان لديك action محلي، فتأكد من وجود ملف action.yml (أو action.yaml/Dockerfile) في المجلد المُستخدم.
      # إذا كان الـ action موجودًا في مجلد فرعي مثلاً "my-action"، فاستخدم:
      - uses: ./my-action
        with:
          sdk: dev
      
      - run: dart pub get
      - run: dart analyze --fatal-infos
      - run: dart tool/sig.dart --verify
      - run: npm run build
